sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
install:
  - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
  - docker run -d --name $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME
script:
  - docker exec -ti $IMAGE_NAME npm run test
after_script:
  - echo 'Done, all looks good folks!'
# Deployment to AWS
deploy:
  #Deployment to AWS
  - provider: elasticbeanstalk
    region: "us-east-2"
    app: "express-docker-app"
    env: "ExpressDockerApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-736607720718"
    bucket_path: "express-docker-app"
    access_key_id: $AWS_ID
    secret_access_key:
      secure: "$AWS_PASSWORD"
    on:
      branch: master
  #Deployment to Heroku
  - provider: script
    script:
      - bash scripts/deploy_heroku.sh
    on:
      branch: staging
  #Deployment to DockerHub
  - provider: script
    script:
      - bash scripts/deploy_dockerhub.sh
    on:
      branch: dockerhub
after_deploy:
  - docker stop $IMAGE_NAME